#include <bits/stdc++.h>
using namespace std;

/*
389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:
Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

*/

char findTheDifference(string s, string t)
{
  map<char, int> mpp;
  for (int i = 0; i < s.size(); i++)
  {
    mpp[s[i]]++;
  }
  for (int i = 0; i < t.size(); i++)
  {
    mpp[t[i]]--;
  }
  for (auto i : mpp)
  {
    if (i.second == -1)
    {
      return i.first;
    }
  }
  return 0;
}

int main()
{
  string s;
  string t;
  cout << "enter a string: ";
  cin >> s;
  cout << "enter another string: ";
  cin >> t;
  cout << findTheDifference(s, t);
}